version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages # Install and automatically cache packages
      - run: npm run build
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages # Install and automatically cache packages
      - run: ./scripts/install-pandoc.sh
      - run: node ./scripts/pre-publish
      - run: npm run build
      - run: npx semantic-release

workflows:
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test